# Generated by Django 5.0.2 on 2024-02-15 13:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Epic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jiraIssueType', models.CharField(default='Epic', max_length=5)),
                ('jiraProject', models.CharField(default='', max_length=100)),
                ('jiraKey', models.CharField(default='', max_length=20)),
                ('jiraEpicName', models.CharField(default='', max_length=1000)),
                ('jiraStatus', models.CharField(default='', max_length=200)),
                ('jiraAssignee', models.CharField(default='', max_length=200)),
                ('jiraCreatedDate', models.DateTimeField()),
                ('jiraUpdatedDate', models.DateTimeField()),
                ('jiraResolvedDate', models.DateTimeField()),
                ('classification', models.CharField(default='', max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s_set', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
