# Generated by Django 5.0.2 on 2024-02-16 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epic', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='epic',
            name='jiraResolvedDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
